### ISSUE TITLE
`#[axum::debug_handler]` produces error when using `Path<Cow<'_, str>>`

### ISSUE THREAD

**Issue by forbjok** [tokio-rs/axum#1377] opened 2022-09-15 17:17 UTC
### Version

0.6.0-rc.2

### Platform

Windows 10 x64

### Description

`#[axum::debug_handler]` produces an error when using `Cow<'_, str>` in a Path<> parameter, but if the macro is commented out, the same code compiles and runs just fine.
I don't know if there is any benefit to using a Cow at all here, but if the code is valid and compiles the macro probably shouldn't complain about it either.

Minimal reproduction:
[axumtest.zip](https://github.com/tokio-rs/axum/files/9577526/axumtest.zip)

**Comment by jplatte** [comment] 2022-09-15 17:20
Using `Cow` with a serde-based deserializer is only useful in combination with `serde(borrow)`, if at all (I'm not entirely certain). Using `Path<Cow<'_, T>>` over `Path<T>` is not useful.

**Comment by davidpdrsn** [comment] 2022-09-18 18:55
I agree that using `Path<Cow<'_, str>>` doesn't really make sense but we should investigate if we can prevent `#[debug_handler]` producing errors, where there otherwise wouldn't be any. Thats sorta the opposite of what its intended for 😜

**Comment by davidpdrsn** [comment] 2023-03-03 09:09
I'm not sure what changed but I can't reproduce this

```rust
#[debug_handler]
async fn handler(_: Path<Cow<'static, str>>) {}
```

works.

I'll close this for now. @forbjok please let us know if you're still seeing this in the latest version.

**Closed by davidpdrsn** 2023-03-03 09:09 UTC
Labels: C-bug, A-axum-macros
