### ISSUE TITLE
I'm facing a memory leak

### ISSUE THREAD

**Issue by zmlgit** [tokio-rs/axum#1577] opened 2022-11-26 09:56 UTC
### Version 
0.6.0,0.5.8

### Platform
Mac and Linux 
### Description

when I post a huge body for times, the memory using grows fast , but when the request ended,the memory dosen't  flow down.

 the code repository is git@github.com:zmlgit/cecs.git ,(I tried mysql (branch master) and pg (branch postgres), all the same) ,

my test data is from https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/villages.json 

the request is curl -XPOST -d @villages.json -H 'Content-Type: application/json' http://localhost:3000/area/village

that's all I found 

thank you

**Comment by davidpdrsn** [comment] 2022-11-26 10:16
Are you sure it is actually a leak and not just the allocator not giving the memory back to the OS?

**Comment by zmlgit** [comment] 2022-11-26 18:51
> 

the memory grows fast, when I request the url in multi threads,when the req end, it's memory using keep over 1G,  it seems there's  no limit. 

is there a way to limit memory allocate?
 

> Are you sure it is actually a leak and not just the allocator not giving the memory back to the OS?

**Comment by davidpdrsn** [comment] 2022-11-26 19:05
That doesn't mean it's a leak. If you send lots of requests with lots of data, without any limits, then memory usage will grow. High memory usage doesn't mean a leak. A leak is when the memory is never freed.

I recommend you research how to debug memory leaks in Rust in general. I don't have much experience doing that myself. Perhaps someone on [the rust users forum](https://users.rust-lang.org) can help.

I think I'll close this for now since I'm pretty confident it's not an issue with axum.

**Closed by davidpdrsn** 2022-11-26 19:05 UTC

**Comment by gitmalong** [comment] 2022-12-19 16:47
@zmlgit are you still facing this issue or have you found a solution? Asking because I am also experiencing a memory leak and cannot really tell why / have not made a reproducable minimal example yet.

**Comment by lcmgh** [comment] 2023-01-25 09:27
Using https://docs.rs/mimalloc/0.1.34/mimalloc/ fixed the issue on my side.

**Comment by lcmgh** [comment] 2023-01-26 08:24
I stand corrected. Memory leak still appears.
