### ISSUE TITLE
bug with / in nest

### ISSUE THREAD

**Issue by mortifia** [tokio-rs/axum#2267] opened 2023-10-11 12:49 UTC
- [x] I have looked for existing issues (including closed) about this

### Version

```
── axum v0.6.20
│   ├── axum-core v0.3.4
│   │       ├── axum v0.6.20 (*)
    ├── axum v0.6.20 (*)
```

### Platform

Linux mortifia 6.5.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:48:15 UTC 2023 x86_64 GNU/Linux

### Description

```rust
    let app = Router::new()
        .route("/", get(hello_world))
        .nest("/advertisement", advertisement::router())
        
  ...... (advertisement::router)
  
  pub fn router() -> Router {
    Router::new()
        .route("/", get(advertisement))
        .route("/:id", get(advertisement_id))
}
```

GET `http://localhost:3000/advertisement` -> `.route("/", get(advertisement))`
GET `http://localhost:3000/advertisement/xxxx` -> `.route("/:id", get(advertisement_id))`
GET `http://localhost:3000/advertisement/` -> `HTTP ERROR 404`   // is the bug

but is the same path

expected

GET `http://localhost:3000/advertisement/` -> `.route("/", get(advertisement))`

**Comment by pauliyobo** [comment] 2023-10-20 18:40
Hello.
Is it a bug, though?
By looking at the code such as:

https://github.com/tokio-rs/axum/blob/8854e660e9ab07404e5bb8e30b92311d3848de05/axum/src/routing/tests/mod.rs?#L319-L330

Or

https://github.com/tokio-rs/axum/blob/8854e660e9ab07404e5bb8e30b92311d3848de05/axum/src/routing/path_router.rs?#L479-L490

it would seem that this behaviour is actually deliberate.
I might be wrong though and please correct me if so.

**Comment by mortifia** [comment] 2023-10-23 22:19
what the RFC says is that if a route with the / at the end is not clearly defined
it will match the route without the / at the end

(implicit rule added by the crawler if I understood correctly)

https://www.rfc-editor.org/rfc/rfc3986

**Comment by Conner-PYS** [comment] 2023-11-01 23:42
I encountered this same behavior while testing my server; though, I don't use any nested routers. From what I could find in other issues and discussions was that this behavior is intended.

As a work-around in my implementation, I have used tower_http's `NormalizePath` layer, which has an implementation to strip trailing slashes. Docs are at 
[https://docs.rs/tower-http/latest/tower_http/normalize_path/index.html].

**Comment by kekorder** [comment] 2023-11-03 19:44
I find this behaviour odd, if its a route with only a slash it ignores that slash for the route, but if it has has `/test/` for example it forces the trailing slash, while I also want the `/nest/` to force a trailing slash.

```rs
use axum::{routing::get, Router};

#[tokio::main]
async fn main() {
    let nest_routes = Router::new()
        .route("/", get(|| async { "http://127.0.0.1/nest/\n" })) // both http://127.0.0.1/nest (only works without a trailing slash)
        .route("/test/", get(|| async { "http://127.0.0.1/nest/test/\n" })); // both http://127.0.0.1/nest/test/ (only works with a traling slash)

    let app = Router::new()
        .route("/", get(|| async { "http://127.0.0.1/\n" })) // both http://127.0.0.1 and http://127.0.0.1/
        .route("/test/", get(|| async { "http://127.0.0.1/test/\n" })) // http://127.0.0.1/test/ (only works with a trailing slash)
        .nest("/nest", nest_routes);
    axum::Server::bind(&"127.0.0.1:8080".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

**Comment by dalton-oliveira** [comment] 2024-01-16 20:27
There is test that asserts the scenario described on this issue. It shows that it must _not_ match trailing slash root uri on nested `Router` but should on nested `Service` 
https://github.com/tokio-rs/axum/blob/94901e0fe798d0fb38b9e6d122376c15264ca46a/axum/src/routing/tests/nest.rs#L351-L384

I did a PR #2524 that fixes #2252 which could change the behavior discussed here, but I'm unsure if that's the desired action to do based on the test.

**Comment by Rodion-Bozhenko** [comment] 2024-02-01 17:37
Hey everyone,
I also stumbled upon an with this issue. The Axum docs suggest a workaround using middleware to rewrite the request URI https://docs.rs/axum/latest/axum/middleware/index.html#rewriting-request-uri-in-middleware, so I came up with this function to remove the trailing slash before the request hits the router:

```Rust
fn rewrite_request_uri<B>(mut req: Request<B>) -> Request<B> {
        let uri = req.uri().clone();
        let path = uri.path();

        if path.ends_with('/') && !path.ends_with("//") && path.len() > 1 {
            let new_path = path.trim_end_matches('/');
            let new_uri = format!(
                "{}{}",
                new_path,
                uri.query().map_or(String::from(""), |q| format!("?{}", q))
            );

            *req.uri_mut() = new_uri.parse().expect("Failed to parse new URI");
        }

        req
    }
```

Note !path.ends_with("//") condition which prevents rewriting urls with multiple slashes. If you need to strip away all  trailing slashes remove this part.

I'm not entirely sure if this is the best approach, but it's been working well for me. If anyone has suggestions for improvement or alternative methods, I'd love to hear them.

**Comment by jplatte** [comment] 2024-03-17 20:55
It took me a while to understand this bug report. It is actually intended behavior, there's some previous discussion about this [here](https://github.com/tokio-rs/axum/issues/714). I'm going to close this as it's framed as a bug report while the behavior is actually intentional, but have created #2659 as a point of discussion about changing this behavior.

**Closed by jplatte** 2024-03-17 20:55 UTC
Labels: C-bug, A-axum

**Comment by mladedav** [comment] 2024-03-17 23:03
First, there is `route_with_tsr` in `axum-extra` which adds redirects between the , so this could be of interest?

There used to be automatic redirects in axum but they were removed in 0.6 #1119

[RFC 3386](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.4) was mentioned, but I read it as saying that the two paths with and without a trailing slash should be considered equivalent only if the server hints that by e.g. redirecting from one to the other.

<details><summary>RFC excerpt</summary>
<p>

```
   Substantial effort to reduce the incidence of false negatives is
   often cost-effective for web spiders.  Therefore, they implement even
   more aggressive techniques in URI comparison.  For example, if they
   observe that a URI such as

      http://example.com/data

   redirects to a URI differing only in the trailing slash

      http://example.com/data/

   they will likely regard the two as equivalent in the future.  This
   kind of technique is only appropriate when equivalence is clearly
   indicated by both the result of accessing the resources and the
   common conventions of their scheme's dereference algorithm (in this
   case, use of redirection by HTTP origin servers to avoid problems
   with relative references).
```

</p>

</details> 

So I think what axum does now is correct and it should not create multiple paths on its own unless instructed to do so.
