### ISSUE TITLE
Performance degradation in release mode compared to debug

### ISSUE THREAD

**Issue by joshualex** [tokio-rs/axum#902] opened 2022-04-02 16:42 UTC
### Version
0.5.0

### Platform
macOS 12.3.1 (M1 Max Apple Silicon)

Darwin ip-192-168-97-129.eu-west-1.compute.internal 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Description
Trying the following simple example:
```rust
use axum::{routing::post, Json, Router};
use serde::Deserialize;

#[tokio::main]
async fn main() {
    // build our application with a route
    let app = Router::new().route("/", post(compute));

    let addr = "127.0.0.1:8000".parse().unwrap();
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}

#[derive(Deserialize)]
struct Params {
    a: u32,
    b: u32,
}

async fn compute(params: Json<Params>) -> String {
    format!("Result is {}", params.a + params.b)
}
```

Running in debug, and then using `hey` to measure performance:

```
$ hey -n 100000 -T application/json -d '{"a": 2, "b": 3}' -m post http://127.0.0.1:8000
```

Under debug build, I get very decent results:
```

Summary:
  Total:	1.5304 secs
  Slowest:	0.0895 secs
  Fastest:	0.0001 secs
  Average:	0.0008 secs
  Requests/sec:	65342.6361

  Total data:	1100000 bytes
  Size/request:	11 bytes

Response time histogram:
  0.000 [1]	|
  0.009 [99872]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.018 [81]	|
  0.027 [21]	|
  0.036 [14]	|
  0.045 [4]	|
  0.054 [3]	|
  0.063 [1]	|
  0.072 [2]	|
  0.081 [0]	|
  0.089 [1]	|


Latency distribution:
  10% in 0.0003 secs
  25% in 0.0005 secs
  50% in 0.0007 secs
  75% in 0.0009 secs
  90% in 0.0012 secs
  95% in 0.0014 secs
  99% in 0.0021 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0000 secs, 0.0001 secs, 0.0895 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0016 secs
  resp wait:	0.0007 secs, 0.0001 secs, 0.0895 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0014 secs

Status code distribution:
  [200]	100000 responses

```

However switching to release build causes performance to degrade considerably, at least as far as total run time goes:

```

Summary:
  Total:	2.7054 secs
  Slowest:	0.0129 secs
  Fastest:	0.0000 secs
  Average:	0.0013 secs
  Requests/sec:	36962.8461

  Total data:	1100000 bytes
  Size/request:	11 bytes

Response time histogram:
  0.000 [1]	|
  0.001 [60141]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.003 [22608]	|■■■■■■■■■■■■■■■
  0.004 [12366]	|■■■■■■■■
  0.005 [3914]	|■■■
  0.006 [813]	|■
  0.008 [121]	|
  0.009 [25]	|
  0.010 [8]	|
  0.012 [0]	|
  0.013 [3]	|


Latency distribution:
  10% in 0.0002 secs
  25% in 0.0003 secs
  50% in 0.0008 secs
  75% in 0.0021 secs
  90% in 0.0032 secs
  95% in 0.0039 secs
  99% in 0.0051 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0000 secs, 0.0000 secs, 0.0129 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0057 secs
  resp wait:	0.0013 secs, 0.0000 secs, 0.0121 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0094 secs

Status code distribution:
  [200]	100000 responses
```

While the time spent in each request indeed became shorter (from 0.009 on average to 0.001-0.002s on average), the overall time is twice as long, and the number of requests per second drops as well.

Any ideas on why this behavior could be happening?

**Comment by davidpdrsn** [comment] 2022-04-02 18:28
Perhaps a silly question but did you perhaps swap what was release and was debug builds? Because I cannot reproduce it. Works fine for me.

Debug numbers:

```
Summary:
  Total:        2.2127 secs
  Slowest:      0.1270 secs
  Fastest:      0.0001 secs
  Average:      0.0011 secs
  Requests/sec: 45193.3280

  Total data:   1100000 bytes
  Size/request: 11 bytes

Response time histogram:
  0.000 [1]     |
  0.013 [99869] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.025 [63]    |
  0.038 [25]    |
  0.051 [13]    |
  0.064 [8]     |
  0.076 [6]     |
  0.089 [7]     |
  0.102 [3]     |
  0.114 [1]     |
  0.127 [4]     |


Latency distribution:
  10% in 0.0005 secs
  25% in 0.0007 secs
  50% in 0.0010 secs
  75% in 0.0013 secs
  90% in 0.0016 secs
  95% in 0.0018 secs
  99% in 0.0030 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0000 secs, 0.0001 secs, 0.1270 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0021 secs
  resp wait:    0.0011 secs, 0.0001 secs, 0.1270 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0024 secs

Status code distribution:
  [200] 100000 responses
```

Release numbers:

```
Summary:
  Total:        0.7336 secs
  Slowest:      0.0113 secs
  Fastest:      0.0000 secs
  Average:      0.0004 secs
  Requests/sec: 136309.8791

  Total data:   1100000 bytes
  Size/request: 11 bytes

Response time histogram:
  0.000 [1]     |
  0.001 [97443] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.002 [2006]  |■
  0.003 [176]   |
  0.005 [101]   |
  0.006 [36]    |
  0.007 [82]    |
  0.008 [60]    |
  0.009 [58]    |
  0.010 [28]    |
  0.011 [9]     |


Latency distribution:
  10% in 0.0001 secs
  25% in 0.0002 secs
  50% in 0.0003 secs
  75% in 0.0004 secs
  90% in 0.0006 secs
  95% in 0.0009 secs
  99% in 0.0016 secs

Details (average, fastest, slowest):
  DNS+dialup:   0.0000 secs, 0.0000 secs, 0.0113 secs
  DNS-lookup:   0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:    0.0000 secs, 0.0000 secs, 0.0092 secs
  resp wait:    0.0003 secs, 0.0000 secs, 0.0094 secs
  resp read:    0.0000 secs, 0.0000 secs, 0.0105 secs

Status code distribution:
  [200] 100000 responses
```

**Comment by joshualex** [comment] 2022-04-02 18:29
@davidpdrsn Nope. Just double checked. Are you also on M1?

**Comment by davidpdrsn** [comment] 2022-04-02 18:30
Yes I am, an M1 air.

**Comment by joshualex** [comment] 2022-04-02 18:35
I'm on M1 Max. I'm guessing this is some misconfiguration with the number of cores in use, perhaps inside Tokio's runtime initialization (which might differ between release and debug?)

**Comment by davidpdrsn** [comment] 2022-04-02 18:40
Hm I have idea 😕 I'm using the exact code you posted. Try asking in #tokio-users in the [tokio discord](https://discord.gg/tokio).

**Comment by davidpdrsn** [comment] 2022-04-03 08:48
I'll close this for now. Don't think there is anything we can do in axum but please post if you figured out what the cause was!

**Closed by davidpdrsn** 2022-04-03 08:48 UTC
