### ISSUE TITLE
lack of a website For Axum

### ISSUE THREAD

**Issue by Imdad-Rind** [tokio-rs/axum#2686] opened 2024-03-28 09:22 UTC
## Feature Request
 Axum Website
 - Axum needs a website visual representation and ease for to find
### Motivation

i am fresh Backend developer and i am learning rust at the moment so i wondered about a Backend framework for Rust so i came upon the Axum and i found out there is now website for it . It feels that something is missing

### Proposal

i would like to Contribute to the creation of the website or the initiation of it , i my self is not good with Frontend but i can help with the backend .
Thank you

### Alternatives

there can many alternative to 
 1 : we can create a simple static HTML and CSS website to give information about
 2 :  we can use website builder ( which i personally don't like) 
 3 :  A full scale web project for Axum

### Thank You

**Comment by jplatte** [comment] 2024-03-28 09:42
Duplicate of #1811.

**Closed by jplatte** 2024-03-28 09:42 UTC
