### ISSUE TITLE
app building fine with rc.2 fails to build with rc.3, in matched_path.rs

### ISSUE THREAD

**Issue by olivier-fs** [tokio-rs/axum#1515] opened 2022-11-09 11:26 UTC
### Version

```
axum = { version = "0.6.0-rc.3", features = ["http1", "json", "tokio"] }
tokio = { version = "1.21.2", default-features = false, features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.3.4", features = ["compression-gzip", "fs", "set-header", "timeout", "trace"] }
```

```shell
$ cargo tree | grep axum
├── axum v0.6.0-rc.3
│   ├── axum-core v0.3.0-rc.3
```
```shell
$ cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

### Platform

Windows 10

### Description

An axum app that was building fine with rc.2 doesn't build with rc.3.
I fixed some breaking but trivial fixes (e.g. nest() => nest_service()) but still :
```shell
$ cargo run --release
   Compiling proc-macro2 v1.0.43
   ...
   ...
   Compiling axum v0.6.0-rc.3
error[E0308]: `if` and `else` have incompatible types
   --> C:\Users\olivier\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.6.0-rc.3\src\extract\matched_path.rs:135:12
    |
133 |       let matched_path = if let Some(matched_path) = route_id_to_path.get(&id) {
    |                          ----------------------------------------------------- `if` and `else` have incompatible types
134 |           matched_path
    |           ------------ expected because of this
135 |       } else {
    |  ____________^
136 | |         #[cfg(debug_assertions)]
137 | |         panic!("should always have a matched path for a route id");
138 | |     };
    | |_____^ expected `&Arc<str>`, found `()`
    |
    = note: expected reference `&Arc<str>`
               found unit type `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `axum` due to previous error
warning: build failed, waiting for other jobs to finish...
```
The odd part is :
- the same code builds fine in debug mode i.e. without --release
- another axum with the "same" setup i.e. route() with get() handlers, nest_service(), and fallback(), builds OK

rustc, that is nearly always giving good details about the problem and the way to fix it, doesn't in my case, and doesn't even give some filename/line featuring the "culprit" code...

Building with nightly (cargo 1.67.0-nightly (9286a1beb 2022-11-04)) doesn't change anything (as expected, it is a simple if let statement, not the new let chain).

The only difference I can spot for now is the failing build has the "json" feature enabled when the one building fine doesn't, but I don't know if it's related in anyway (and removing the feature makes the app build fail for tons of reason because there are json handlers... It would be possible to comment all these if needed, but I post this issue as is for now).

I'll try to spot more differences between the "OK" code and the the failing one.

**Comment by yanns** [comment] 2022-11-09 11:37
I can confirm this issue on Mac and Linux.

**Comment by jplatte** [comment] 2022-11-09 11:44
> the same code builds fine in debug mode i.e. without --release

That is because of the `#[cfg(debug_assertions)]`. I think that just has to be removed for this to work again.

**Comment by jplatte** [comment] 2022-11-09 11:45
I think adding this to your `Cargo.toml` should make it work until we fix it properly:

```rust
[profile.release.package]
axum = { debug = true }
```

**Comment by davidpdrsn** [comment] 2022-11-09 11:47
Ah yes I see. I'll fix that an ship a new release!

**Comment by lolo32** [comment] 2022-11-09 12:20
It's the same for the released rc.4

**Comment by davidpdrsn** [comment] 2022-11-09 12:25
@lolo32 There is no rc.4 so not sure what you mean.

**Comment by olivier-fs** [comment] 2022-11-09 12:32
```
[profile.release.package]
axum = { debug = true }
```
doesn't fix it on my box.

FYI - even if it's almost surely not related at all - I have
```
[profile.release]
strip = true
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
```

Anyway I just wanted to report the issue as soon as possible, because that's the whole point of "rc" releases.
I can revert eaasily revert to rc-2, and wait for the next rc-4 or reference the github version now that the problem is spotted.

I still can't catch what difference in source code makes it build in release mode in one app and not the other...

Still eager to try asap the fantastic work both of you guys are doing on axum ! thanks a lot.

**Comment by davidpdrsn** [comment] 2022-11-09 12:34
When https://github.com/tokio-rs/axum/pull/1517 is merged I'll do a new release.

**Comment by lolo32** [comment] 2022-11-09 12:35
> @lolo32 There is no rc.4 so not sure what you mean.

Sorry, my bad, forget my comment

**Closed** 2022-11-09 12:36 UTC

**Comment by davidpdrsn** [comment] 2022-11-09 12:52
Alright 0.6.0-rc.4 is out with the fix! Thanks for reporting it!
