### ISSUE TITLE
HandleErrorLayer doesn't work?

### ISSUE THREAD

**Issue by edg-l** [tokio-rs/axum#1429] opened 2022-09-28 19:28 UTC
## Feature Request

I want my API to be consistent, but i don't know how to make the error handling for middleware return a JSON body for example, instead of the forced String.

```rust
async fn handle_error(err: BoxError) -> (StatusCode, String) {
    (
        StatusCode::BAD_REQUEST,
        format!("oh noes error! {err:?}");
    )
}
```

To

```rust
async fn handle_error(err: BoxError) -> impl IntoResponse {
    (
        StatusCode::BAD_REQUEST,
        Json(ConvertToConsistentError::new(err))
    ).into_response()
}
```

Or something like that.

I guess there is a reason it's not like this? I would like to know if so!

**Comment by davidpdrsn** [comment] 2022-09-28 19:35
Why did you close this?

What error are you getting?

**Comment by edg-l** [comment] 2022-09-29 18:30
i want to handle

**Comment by edg-l** [comment] 2022-09-29 18:31
because i wasn't sure if it was my own error or something to do with the library, but basically i want to add an error handler in case middleware fails but return a proper json response instead of a string

**Comment by davidpdrsn** [comment] 2022-09-29 19:27
What error are you getting?

**Comment by edg-l** [comment] 2022-09-29 20:50
Just noticed, even when returning (StatusCode, String) it says the trait bound is not satisfied:

```rust
error[E0277]: the trait bound `HandleError<SetSensitiveRequestHeaders<tower_http::trace::Trace<CookieManager<AddExtension<Route, DatabaseConnection>>, SharedClassifier<ServerErrorsAsFailures>>>, fn(Method, Uri, std::boxed::Box<(dyn StdError + Send + Sync + 'static)>) -> impl Future<Output = (http::StatusCode, std::string::String)> {handle_error}, _>: Service<Request<_>>` is not satisfied
   --> src\main.rs:39:10
    |
39  |         .layer(
    |          ^^^^^ the trait `Service<Request<_>>` is not implemented for `HandleError<SetSensitiveRequestHeaders<tower_http::trace::Trace<CookieManager<AddExtension<Route, DatabaseConnection>>, SharedClassifier<ServerErrorsAsFailures>>>, fn(Method, Uri, std::boxed::Box<(dyn StdError + Send + Sync + 'static)>) -> impl Future<Output = (http::StatusCode, std::string::String)> {handle_error}, _>`
    |
    = help: the following other types implement trait `Service<Request>`:
              HandleError<S, F, ()>
              HandleError<S, F, (T1, T2)>
              HandleError<S, F, (T1, T2, T3)>
              HandleError<S, F, (T1, T2, T3, T4)>
              HandleError<S, F, (T1, T2, T3, T4, T5)>
              HandleError<S, F, (T1, T2, T3, T4, T5, T6)>
              HandleError<S, F, (T1, T2, T3, T4, T5, T6, T7)>
              HandleError<S, F, (T1, T2, T3, T4, T5, T6, T7, T8)>
            and 9 others
note: required by a bound in `Router::<B>::layer`
   --> C:\Users\Edgar\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.5.16\src\routing\mod.rs:305:21
    |
305 |         L::Service: Service<Request<NewReqBody>, Response = Response<NewResBody>, Error = Infallible>
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Router::<B>::layer`

For more information about this error, try `rustc --explain E0277`.
warning: `backend` (bin "backend") generated 1 warning
error: could not compile `backend` due to previous error; 1 warning emitted
```

I guess I'm doing something wrong, my router looks like this:

```rust
let app = Router::new()
        .nest("/users", routes::users::routes())
        .nest("/auth", routes::auth::routes())
        .layer(
            ServiceBuilder::new()
                .layer(HandleErrorLayer::new(handle_error))
                .layer(SetSensitiveRequestHeadersLayer::new(once(AUTHORIZATION)))
                .layer(TraceLayer::new_for_http())
                .layer(CookieManagerLayer::new())
                .layer(Extension(conn)),
        );
```

Axum version is 0.5.x

**Comment by davidpdrsn** [comment] 2022-09-29 22:21
Thanks for providing more details!

The issue is that none of those middleware produce any errors. So you have no errors to handle. Then `HandleErrorLayer` gives that error.

The difference is that the example uses a `TimeoutLayer` which does produce errors. See https://docs.rs/axum/0.5.16/axum/error_handling/index.html#axums-error-handling-model more for details.

The solution is simply to not use `HandleErrorLayer` unless you actually use a fallible middleware. You cannot forget and will get a compile if `HandleErrorLayer` becomes necessary.

**Closed** 2022-09-29 22:21 UTC
