### ISSUE TITLE
Fallback panics on CONNECT requests

### ISSUE THREAD

**Issue by Power2All** [tokio-rs/axum#1955] opened 2023-04-22 08:06 UTC
- [X] I have looked for existing issues (including closed) about this

### Version

```
├── axum v0.6.16
│   ├── async-trait v0.1.68 (proc-macro) (*)
│   ├── axum-core v0.3.4
│   │   ├── async-trait v0.1.68 (proc-macro) (*)
│   │   ├── bytes v1.4.0
│   │   ├── futures-util v0.3.28
│   │   │   ├── futures-channel v0.3.28
│   │   │   │   ├── futures-core v0.3.28
│   │   │   │   └── futures-sink v0.3.28
│   │   │   ├── futures-core v0.3.28
│   │   │   ├── futures-io v0.3.28
│   │   │   ├── futures-macro v0.3.28 (proc-macro)
│   │   │   │   ├── proc-macro2 v1.0.56 (*)
│   │   │   │   ├── quote v1.0.26 (*)
│   │   │   │   └── syn v2.0.15 (*)
│   │   │   ├── futures-sink v0.3.28
│   │   │   ├── futures-task v0.3.28
│   │   │   ├── memchr v2.5.0
│   │   │   ├── pin-project-lite v0.2.9
│   │   │   ├── pin-utils v0.1.0
│   │   │   └── slab v0.4.8 (*)
│   │   ├── http v0.2.9
│   │   │   ├── bytes v1.4.0
│   │   │   ├── fnv v1.0.7
│   │   │   └── itoa v1.0.6
│   │   ├── http-body v0.4.5
│   │   │   ├── bytes v1.4.0
│   │   │   ├── http v0.2.9 (*)
│   │   │   └── pin-project-lite v0.2.9
│   │   ├── mime v0.3.17
│   │   ├── tower-layer v0.3.2
│   │   └── tower-service v0.3.2
│   │   [build-dependencies]
│   │   └── rustversion v1.0.12 (proc-macro)
│   ├── bitflags v1.3.2
│   ├── bytes v1.4.0
│   ├── futures-util v0.3.28 (*)
│   ├── http v0.2.9 (*)
│   ├── http-body v0.4.5 (*)
│   ├── hyper v0.14.26
│   │   ├── bytes v1.4.0
│   │   ├── futures-channel v0.3.28 (*)
│   │   ├── futures-core v0.3.28
│   │   ├── futures-util v0.3.28 (*)
│   │   ├── h2 v0.3.18
│   │   │   ├── bytes v1.4.0
│   │   │   ├── fnv v1.0.7
│   │   │   ├── futures-core v0.3.28
│   │   │   ├── futures-sink v0.3.28
│   │   │   ├── futures-util v0.3.28 (*)
│   │   │   ├── http v0.2.9 (*)
│   │   │   ├── indexmap v1.9.3
│   │   │   │   └── hashbrown v0.12.3
│   │   │   │       └── ahash v0.7.6
│   │   │   │           ├── getrandom v0.2.9
│   │   │   │           │   ├── cfg-if v1.0.0
│   │   │   │           │   └── libc v0.2.142
│   │   │   │           └── once_cell v1.17.1
│   │   │   │           [build-dependencies]
│   │   │   │           └── version_check v0.9.4
│   │   │   │   [build-dependencies]
│   │   │   │   └── autocfg v1.1.0
│   │   │   ├── slab v0.4.8 (*)
│   │   │   ├── tokio v1.27.0
│   │   │   │   ├── bytes v1.4.0
│   │   │   │   ├── libc v0.2.142
│   │   │   │   ├── mio v0.8.6
│   │   │   │   │   ├── libc v0.2.142
│   │   │   │   │   └── log v0.4.17 (*)
│   │   │   │   ├── num_cpus v1.15.0
│   │   │   │   │   └── libc v0.2.142
│   │   │   │   ├── parking_lot v0.12.1
│   │   │   │   │   ├── lock_api v0.4.9
│   │   │   │   │   │   └── scopeguard v1.1.0
│   │   │   │   │   │   [build-dependencies]
│   │   │   │   │   │   └── autocfg v1.1.0
│   │   │   │   │   └── parking_lot_core v0.9.7
│   │   │   │   │       ├── cfg-if v1.0.0
│   │   │   │   │       ├── libc v0.2.142
│   │   │   │   │       └── smallvec v1.10.0
│   │   │   │   ├── pin-project-lite v0.2.9
│   │   │   │   ├── signal-hook-registry v1.4.1
│   │   │   │   │   └── libc v0.2.142
│   │   │   │   ├── socket2 v0.4.9 (*)
│   │   │   │   └── tokio-macros v2.0.0 (proc-macro)
│   │   │   │       ├── proc-macro2 v1.0.56 (*)
│   │   │   │       ├── quote v1.0.26 (*)
│   │   │   │       └── syn v2.0.15 (*)
│   │   │   │   [build-dependencies]
│   │   │   │   └── autocfg v1.1.0
│   │   │   ├── tokio-util v0.7.7
│   │   │   │   ├── bytes v1.4.0
│   │   │   │   ├── futures-core v0.3.28
│   │   │   │   ├── futures-sink v0.3.28
│   │   │   │   ├── pin-project-lite v0.2.9
│   │   │   │   ├── tokio v1.27.0 (*)
│   │   │   │   └── tracing v0.1.37
│   │   │   │       ├── cfg-if v1.0.0
│   │   │   │       ├── log v0.4.17 (*)
│   │   │   │       ├── pin-project-lite v0.2.9
│   │   │   │       └── tracing-core v0.1.30
│   │   │   │           └── once_cell v1.17.1
│   │   │   └── tracing v0.1.37 (*)
│   │   ├── http v0.2.9 (*)
│   │   ├── http-body v0.4.5 (*)
│   │   ├── httparse v1.8.0
│   │   ├── httpdate v1.0.2
│   │   ├── itoa v1.0.6
│   │   ├── pin-project-lite v0.2.9
│   │   ├── socket2 v0.4.9 (*)
│   │   ├── tokio v1.27.0 (*)
│   │   ├── tower-service v0.3.2
│   │   ├── tracing v0.1.37 (*)
│   │   └── want v0.3.0
│   │       ├── log v0.4.17 (*)
│   │       └── try-lock v0.2.4
│   ├── itoa v1.0.6
│   ├── matchit v0.7.0
│   ├── memchr v2.5.0
│   ├── mime v0.3.17
│   ├── percent-encoding v2.2.0
│   ├── pin-project-lite v0.2.9
│   ├── serde v1.0.160
│   │   └── serde_derive v1.0.160 (proc-macro)
│   │       ├── proc-macro2 v1.0.56 (*)
│   │       ├── quote v1.0.26 (*)
│   │       └── syn v2.0.15 (*)
│   ├── serde_json v1.0.96
│   │   ├── itoa v1.0.6
│   │   ├── ryu v1.0.13
│   │   └── serde v1.0.160 (*)
│   ├── serde_path_to_error v0.1.11
│   │   └── serde v1.0.160 (*)
│   ├── serde_urlencoded v0.7.1
│   │   ├── form_urlencoded v1.1.0
│   │   │   └── percent-encoding v2.2.0
│   │   ├── itoa v1.0.6
│   │   ├── ryu v1.0.13
│   │   └── serde v1.0.160 (*)
│   ├── sync_wrapper v0.1.2
│   ├── tokio v1.27.0 (*)
│   ├── tower v0.4.13
│   │   ├── futures-core v0.3.28
│   │   ├── futures-util v0.3.28 (*)
│   │   ├── pin-project v1.0.12
│   │   │   └── pin-project-internal v1.0.12 (proc-macro)
│   │   │       ├── proc-macro2 v1.0.56 (*)
│   │   │       ├── quote v1.0.26 (*)
│   │   │       └── syn v1.0.109 (*)
│   │   ├── pin-project-lite v0.2.9
│   │   ├── tokio v1.27.0 (*)
│   │   ├── tower-layer v0.3.2
│   │   ├── tower-service v0.3.2
│   │   └── tracing v0.1.37 (*)
│   ├── tower-layer v0.3.2
│   └── tower-service v0.3.2
│   [build-dependencies]
│   └── rustversion v1.0.12 (proc-macro)
├── axum-client-ip v0.4.0
│   ├── axum v0.6.16 (*)
│   ├── forwarded-header-value v0.1.1
│   │   ├── nonempty v0.7.0
│   │   └── thiserror v1.0.40
│   │       └── thiserror-impl v1.0.40 (proc-macro)
│   │           ├── proc-macro2 v1.0.56 (*)
│   │           ├── quote v1.0.26 (*)
│   │           └── syn v2.0.15 (*)
│   └── serde v1.0.160 (*)
├── axum-server v0.4.7
│   ├── arc-swap v1.6.0
│   ├── bytes v1.4.0
│   ├── futures-util v0.3.28 (*)
│   ├── http v0.2.9 (*)
│   ├── http-body v0.4.5 (*)
│   ├── hyper v0.14.26 (*)
│   ├── pin-project-lite v0.2.9
│   ├── rustls v0.20.8
│   │   ├── log v0.4.17 (*)
│   │   ├── ring v0.16.20
│   │   │   ├── libc v0.2.142
│   │   │   ├── once_cell v1.17.1
│   │   │   ├── spin v0.5.2
│   │   │   └── untrusted v0.7.1
│   │   │   [build-dependencies]
│   │   │   └── cc v1.0.79
│   │   ├── sct v0.7.0
│   │   │   ├── ring v0.16.20 (*)
│   │   │   └── untrusted v0.7.1
│   │   └── webpki v0.22.0
│   │       ├── ring v0.16.20 (*)
│   │       └── untrusted v0.7.1
│   ├── rustls-pemfile v1.0.2
│   │   └── base64 v0.21.0
│   ├── tokio v1.27.0 (*)
│   ├── tokio-rustls v0.23.4
│   │   ├── rustls v0.20.8 (*)
│   │   ├── tokio v1.27.0 (*)
│   │   └── webpki v0.22.0 (*)
│   └── tower-service v0.3.2
```

### Platform

Ubuntu 22.04

### Description

There is a bug it seems in the Axum code of 0.6.16 where it reaches unreachable code, and panic errors.
```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.16/src/routing/mod.rs:312:45
```

I tried to cleanup the registry and re-download and re-compile the code, but it still happens.
Going to downgrade it a minor version, and see if it happens on former versions.
Will report and edit this post if I got any.

**Comment by davidpdrsn** [comment] 2023-04-22 08:11
Can you provide a reproduction script? Not much we can do when you don't post any code.

**Comment by Power2All** [comment] 2023-04-22 08:13
@davidpdrsn I'm not sure, since it's not my code giving the error.
However, you can look into the project itself using it:
https://github.com/Power2All/torrust-axum/tree/v3.2.0
You can find the downgrade push there as well.

**Comment by davidpdrsn** [comment] 2023-04-22 08:56
> I'm not sure, since it's not my code giving the error.

But you're using axum and hitting this error. I need to see how you manage to do that.

> you can look into the project itself using it:

That's a big project. Do you have a smaller reproduction?

**Comment by Power2All** [comment] 2023-04-22 11:51
This is the exact trace:

`thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: the default fallback added in `Router::new` matches everything', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.16/src/routing/mod.rs:318:25
stack backtrace:
   0:     0x562b09a91839 - <unknown>
   1:     0x562b0995fc1e - <unknown>
   2:     0x562b09a6dda4 - <unknown>
   3:     0x562b09a928cf - <unknown>
   4:     0x562b09a924cf - <unknown>
   5:     0x562b09a93538 - <unknown>
   6:     0x562b09a93022 - <unknown>
   7:     0x562b09a92f8c - <unknown>
   8:     0x562b09a92f61 - <unknown>
   9:     0x562b0985a0a2 - <unknown>
  10:     0x562b098c954d - <unknown>
  11:     0x562b0986a1e0 - <unknown>
  12:     0x562b098b7db6 - <unknown>
  13:     0x562b098c2207 - <unknown>
  14:     0x562b098dba4e - <unknown>
  15:     0x562b098bef30 - <unknown>
  16:     0x562b09a986a8 - <unknown>
  17:     0x562b09aa13d5 - <unknown>
  18:     0x562b09a9750d - <unknown>
  19:     0x562b09a971e6 - <unknown>
  20:     0x562b09a9c615 - <unknown>
  21:     0x562b09a94265 - <unknown>
  22:     0x7f958e507b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  23:     0x7f958e599a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  24:                0x0 - <unknown>
Aborted
`

**Comment by Power2All** [comment] 2023-04-22 12:28
Update:
Tested until v0.6.12 and that looks to be stable.
v0.6.13 showed a ton of debugging messages, so I didn't try use that to see if it crashed.
Since v0.6.13+ the code became unstable and crashes with the previous post with tracelog data.
Please investigate, as this doesn't seem to be related to my own code.

**Comment by davidpdrsn** [comment] 2023-04-22 12:45
> Please investigate, as this doesn't seem to be related to my own code.

It's a bug in axum sure, but I need a way to _reproduce_ the bug. You gotta help me help you by providing a way to reproduce it.

**Comment by Power2All** [comment] 2023-04-22 12:47
> > Please investigate, as this doesn't seem to be related to my own code.
> 
> It's a bug in axum sure, but I need a way to _reproduce_ the bug. You gotta help me help you by providing a way to reproduce it.

I'm not sure how to.
It happens when I activate the app, since I deal with thousands of request per second, it hits this error eventually. What would you like me to test or how ?

**Comment by davidpdrsn** [comment] 2023-04-22 12:51
- Log the request that causes the panic
- Send that request yourself and see you can repro the panic consistently
- Then reproduce that with a smaller amount of code until you find a minimal way to reproduce it

I'm not sure what you expect me to do. Do you want me to run your app and randomly send it requests until I hit the bug? Sorry but I can't do that.

**Comment by Power2All** [comment] 2023-04-22 13:08
> * Log the request that causes the panic
> 
>     * Send that request yourself and see you can repro the panic consistently
> 
>     * Then reproduce that with a smaller amount of code until you find a minimal way to reproduce it
> 
> 
> I'm not sure what you expect me to do. Do you want me to run your app and randomly send it requests until I hit the bug? Sorry but I can't do that.
> 
> Without a way to reproduce it how can I know if my changes to axum have actually fixed it?

I'll see what I can do.
As I said, I get a ton of connection requests on the server, so trying to catch that single request is going to take some time, since my Rust is not nearly close to being "good", since I've been learning Rust after GoLang was failing on me.

**Comment by davidpdrsn** [comment] 2023-04-22 13:14
I've tried making a test with all the routes your app has:

```rust
#[tokio::test]
async fn foobar() {
    async fn handler() {}

    let app = Router::new()
        .route("/webgui/*path", get(handler))
        .route("/api/stats", get(handler))
        .route("/api/torrent/:info_hash", get(handler).delete(handler))
        .route("/api/torrents", get(handler))
        .route("/api/whitelist", get(handler))
        .route("/api/whitelist/reload", get(handler))
        .route(
            "/api/whitelist/:info_hash",
            get(handler).post(handler).delete(handler),
        )
        .route("/api/blacklist", get(handler))
        .route("/api/blacklist/reload", get(handler))
        .route(
            "/api/blacklist/:info_hash",
            get(handler).post(handler).delete(handler),
        )
        .route("/api/keys", get(handler))
        .route("/api/keys/reload", get(handler))
        .route("/api/keys/:key", get(handler).delete(handler))
        .route(
            "/api/keys/:key/:seconds_valid",
            post(handler).patch(handler),
        )
        .route("/api/maintenance/enable", get(handler))
        .route("/api/maintenance/disable", get(handler))
        .route("/announce", get(handler))
        .route("/announce/:key", get(handler))
        .route("/scrape", get(handler))
        .route("/scrape/:key", get(handler))
        // doesn't matter if we leave this on or not
        .fallback(|| async {});

    let client = TestClient::new(app);

    client.get("/foo").send().await;
}
```

but that doesn't hit it. It's got something to do with fallbacks so maybe it's a request for an unmatched route.

I would also have guessed nesting was involved but you don't use `Router::nest` it seems 🤔c

**Comment by Power2All** [comment] 2023-04-22 13:26
I'm about to leave Turkey (holiday), will try and add a request logger to determine what request might possibly do this.

**Comment by Power2All** [comment] 2023-04-24 08:38
@davidpdrsn Do you know how I could simply apply a "access.log" kind of logger to Axum?
As I said, my Rust knowledge is not that high yet, and I'm still learning good practices, so I wondered if you could show me or tell me how I could simply can add a Apache like logging method to Axum, so I can start logging this to a file until it crashes, thus we know which request does the panic error.

**Comment by davidpdrsn** [comment] 2023-04-24 08:58
Hm I just realized that since the panic happens inside axum during routing, and middleware run after routing, its not as simple as I would have thought 🤔 I'll work on it today and try and come up with an example for you.

This code path is going away in the next major version of axum (https://github.com/tokio-rs/axum/pull/1956) so won't be problem then (but we should still fix it of course)

**Comment by davidpdrsn** [comment] 2023-04-24 09:10
This seems to work:

```rust
// Cargo.toml:
//
// ```toml
// [dependencies]
// axum = "0.6"
// tokio = { version = "1.0", features = ["full"] }
// tracing = "0.1"
// tracing-subscriber = { version = "0.3", features = ["env-filter"] }
// futures = "0.3"

// # required because of tracing-subscriber bug
// regex = { version = "1", features = ["unicode-case"] }
// ```

use axum::{
    http::{HeaderMap, Method, Request, StatusCode, Uri},
    middleware::{from_fn, Next},
    response::{IntoResponse, Response},
    routing::{get, MethodRouter},
    Router,
};
use futures::FutureExt;
use std::{
    any::Any,
    net::SocketAddr,
    panic::{catch_unwind, AssertUnwindSafe},
};

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let app = Router::new().route("/", get(|| async { "OK" }));

    // we have to apply the middleware around the whole router
    // because middleware run after routing, so if a panic happens during routing
    // middleware normally wont see them
    let app_with_panic_logging: MethodRouter =
        axum::routing::any_service(app).layer(from_fn(log_panic));

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::debug!("listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app_with_panic_logging.into_make_service())
        .await
        .unwrap();
}

async fn log_panic<B>(request: Request<B>, next: Next<B>) -> Response {
    let method = request.method().clone();
    let uri = request.uri().clone();
    let headers = request.headers().clone();

    let future = match catch_unwind(AssertUnwindSafe(|| next.run(request))) {
        Ok(future) => future,
        Err(err) => {
            return handle_panic(&method, &uri, &headers, err);
        }
    };

    match AssertUnwindSafe(future).catch_unwind().await {
        Ok(response) => response,
        Err(err) => handle_panic(&method, &uri, &headers, err),
    }
}

fn handle_panic(
    method: &Method,
    uri: &Uri,
    headers: &HeaderMap,
    err: Box<dyn Any + Send>,
) -> Response {
    let details = if let Some(s) = err.downcast_ref::<String>() {
        s.clone()
    } else if let Some(s) = err.downcast_ref::<&str>() {
        s.to_string()
    } else {
        "Unknown panic message".to_string()
    };

    tracing::error!(details, ?method, ?uri, ?headers, "request panicked");

    StatusCode::INTERNAL_SERVER_ERROR.into_response()
}
```

**Comment by Power2All** [comment] 2023-04-24 09:20
> This seems to work:
> 
> ```rust
> // Cargo.toml:
> //
> // ```toml
> // [dependencies]
> // axum = "0.6"
> // tokio = { version = "1.0", features = ["full"] }
> // tracing = "0.1"
> // tracing-subscriber = { version = "0.3", features = ["env-filter"] }
> // futures = "0.3"
> 
> // # required because of tracing-subscriber bug
> // regex = { version = "1", features = ["unicode-case"] }
> // ```
> 
> use axum::{
>     http::{HeaderMap, Method, Request, StatusCode, Uri},
>     middleware::{from_fn, Next},
>     response::{IntoResponse, Response},
>     routing::{get, MethodRouter},
>     Router,
> };
> use futures::FutureExt;
> use std::{
>     any::Any,
>     net::SocketAddr,
>     panic::{catch_unwind, AssertUnwindSafe},
> };
> 
> #[tokio::main]
> async fn main() {
>     tracing_subscriber::fmt::init();
> 
>     let app = Router::new().route("/", get(|| async { "OK" }));
> 
>     // we have to apply the middleware around the whole router
>     // because middleware run after routing, so if a panic happens during routing
>     // middleware normally wont see them
>     let app_with_panic_logging: MethodRouter =
>         axum::routing::any_service(app).layer(from_fn(log_panic));
> 
>     let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
>     tracing::debug!("listening on {}", addr);
>     axum::Server::bind(&addr)
>         .serve(app_with_panic_logging.into_make_service())
>         .await
>         .unwrap();
> }
> 
> async fn log_panic<B>(request: Request<B>, next: Next<B>) -> Response {
>     let method = request.method().clone();
>     let uri = request.uri().clone();
>     let headers = request.headers().clone();
> 
>     let future = match catch_unwind(AssertUnwindSafe(|| next.run(request))) {
>         Ok(future) => future,
>         Err(err) => {
>             return handle_panic(&method, &uri, &headers, err);
>         }
>     };
> 
>     match AssertUnwindSafe(future).catch_unwind().await {
>         Ok(response) => response,
>         Err(err) => handle_panic(&method, &uri, &headers, err),
>     }
> }
> 
> fn handle_panic(
>     method: &Method,
>     uri: &Uri,
>     headers: &HeaderMap,
>     err: Box<dyn Any + Send>,
> ) -> Response {
>     let details = if let Some(s) = err.downcast_ref::<String>() {
>         s.clone()
>     } else if let Some(s) = err.downcast_ref::<&str>() {
>         s.to_string()
>     } else {
>         "Unknown panic message".to_string()
>     };
> 
>     tracing::error!(details, ?method, ?uri, ?headers, "request panicked");
> 
>     StatusCode::INTERNAL_SERVER_ERROR.into_response()
> }
> ```

Alright, I'll try and implement it :)

**Comment by Power2All** [comment] 2023-04-24 09:32
@davidpdrsn What should I do with this ?
![image](https://user-images.githubusercontent.com/2010549/233958054-ad9de0d0-4a64-455f-9d57-2018f6338ae5.png)

**Comment by Power2All** [comment] 2023-04-24 09:39
Another error I try to figure out:
![image](https://user-images.githubusercontent.com/2010549/233959820-9cbed6be-829f-421f-b5da-7b189f6e326d.png)

**Comment by davidpdrsn** [comment] 2023-04-24 09:57
Great! Thanks :D

**Comment by Power2All** [comment] 2023-04-24 10:15
> Great! Thanks :D

Alright, I'm running it with the new code enabled now to stdout and stderr log files.
If anything happens, it should be logged in those files, so I can share the output with you here.

**Comment by Power2All** [comment] 2023-04-24 10:51
Sadly, no return data is given.
Same error as before:
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.16/src/routing/mod.rs:312:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jplatte** [comment] 2023-04-24 10:53
Maybe add `RUST_BACKTRACE=1` to the environment variables for your process as suggested by the error message? A backtrace could be helpful.

**Comment by Power2All** [comment] 2023-04-24 10:54
> Maybe add `RUST_BACKTRACE=1` to the environment variables for your process as suggested by the error message? A backtrace could be helpful.

Running now with `RUST_BACKTRACE=1 ./torrust-axum > stdout.log 2> stderr.log` and see what it shows.

**Comment by davidpdrsn** [comment] 2023-04-24 11:27
> Sadly, no return data is given.

Do you mean that nothing gets logged? I guess you didn't configure the logging correctly. How did you do it?

**Comment by davidpdrsn** [comment] 2023-04-24 13:41
I pushed a commit (07cd3c8f4f281) that always panics in the router similarly to that real issue. Try to use that commit of axum instead:

```toml
axum = { git = "https://github.com/tokio-rs/axum", rev = "07cd3c8f4f281" }
```

Then you can debug your logging setup as it'll panic on all requests.

Obviously don't push this rev to production 😅

**Comment by Power2All** [comment] 2023-04-24 13:53
> ```toml
> https://github.com/tokio-rs/axum
> ```

![image](https://user-images.githubusercontent.com/2010549/234017219-9a63a72d-c4de-419e-b889-4dd669791aef.png)

What might be the case ?
Something is unsatisfied, not sure why, using your git branch.

**Comment by davidpdrsn** [comment] 2023-04-24 13:56
Sorry my bad. You need to use a patch:

```toml
# bottom of Cargo.toml
[patch.crates-io]
axum = { git = "https://github.com/tokio-rs/axum", rev = "07cd3c8f4f281" }
```

I've verified that that at least builds.

**Comment by Power2All** [comment] 2023-04-24 14:09
> Sorry my bad. You need to use a patch:
> 
> ```toml
> # bottom of Cargo.toml
> [patch.crates-io]
> axum = { git = "https://github.com/tokio-rs/axum", rev = "07cd3c8f4f281" }
> ```
> 
> I've verified that that at least builds.

Gives this:

```
warning: Patch `axum v0.6.16 (https://github.com/tokio-rs/axum?rev=07cd3c8f4f281#07cd3c8f)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

I wonder if the patch is applied with this warning though.
So far not triggering the panic on my local machine, but it happens at random times on the live environment.

**Comment by Power2All** [comment] 2023-04-24 14:10
> Sorry my bad. You need to use a patch:
> 
> ```toml
> # bottom of Cargo.toml
> [patch.crates-io]
> axum = { git = "https://github.com/tokio-rs/axum", rev = "07cd3c8f4f281" }
> ```
> 
> I've verified that that at least builds.

Works.
Locally shows a panic error on every response.

**Comment by davidpdrsn** [comment] 2023-04-24 14:12
And do you see anything the logs from the middleware?

**Comment by davidpdrsn** [comment] 2023-04-24 14:18
I don't understand. If https://github.com/tokio-rs/axum/blob/07cd3c8f4f2815557f994b17755886b18315d392/axum/src/routing/mod.rs#L310 hits the middleware then why doesn't https://github.com/tokio-rs/axum/blob/07cd3c8f4f2815557f994b17755886b18315d392/axum/src/routing/mod.rs#L315 🤔

**Comment by Power2All** [comment] 2023-04-24 14:20
> I don't understand. If
> 
> https://github.com/tokio-rs/axum/blob/07cd3c8f4f2815557f994b17755886b18315d392/axum/src/routing/mod.rs#L310
> hits the middleware then why doesn't
> 
> https://github.com/tokio-rs/axum/blob/07cd3c8f4f2815557f994b17755886b18315d392/axum/src/routing/mod.rs#L315
> 🤔

If you like, I could give 0.6.13 a try, and if that doesn't die almost instantly, 0.6.14.
Between 0.6.12 and 0.6.16 something changed that it do this.

**Comment by davidpdrsn** [comment] 2023-04-24 14:20
I guess way to go about it is to put the request info in the panic message itself. I did that in d935c1b8fd658. Try to run with that.

**Comment by davidpdrsn** [comment] 2023-04-24 15:48
No. Those headers don't influence the routing, which is where the panic is coming from. I really don't understand how that request could hit it. It should just go to the fallback like any other request.

**Comment by Power2All** [comment] 2023-04-24 15:59
> No. Those headers don't influence the routing, which is where the panic is coming from. I really don't understand how that request could hit it. It should just go to the fallback like any other request.

Good question.
You want me to try to see which version exactly crashes the system ?

**Comment by davidpdrsn** [comment] 2023-04-24 16:10
Which version of axum? I would expect that to be 0.6.13, 0.6.14, 0.6.15, and 0.6.16. Those versions all have the code path that panics, previous versions don't.

What would be more helpful would be if you can run your app locally, send it the request we're seeing (sending `CONNECT` requests is always annoying), and see if you can get the panic. I've tried that myself in a separate project with the same routes but I couldn't get it to panic.

**Comment by Power2All** [comment] 2023-04-24 17:33
> 

Somehow could we dump the raw data in base64 somewhere to a file if it triggers the panic ?
That way, we could look into the full request if there is anything it trips on.

**Comment by davidpdrsn** [comment] 2023-04-24 18:24
> Somehow could we dump the raw data in base64 somewhere to a file if it triggers the panic ?

You mean the raw request? No I don't think that's possible.

**Comment by Power2All** [comment] 2023-04-24 19:50
> > Somehow could we dump the raw data in base64 somewhere to a file if it triggers the panic ?
> 
> You mean the raw request? No I don't think that's possible.

Mmm that's sad.
Would have been easy to replay the issue with a raw request, which you can send to the client, thus it would crash (possibly) again. Do you have anything else you like me to try ?

**Comment by Power2All** [comment] 2023-04-24 20:19
```
path_router hit
path_router hit
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.13/src/routing/mod.rs:315:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

It's defenitely happening since v0.6.13

**Comment by davidpdrsn** [comment] 2023-04-24 20:36
I've pushed another commit that includes the whole router in the panic message. I'm curious to see which paths the fallback router has internally. Sha is 264462131f00e. Are you able to test with that?

Thanks for being so engaged with testing by the way! This is slowly driving me crazy 😅

**Comment by Power2All** [comment] 2023-04-24 20:38
> 

No worries, I had my time on brain cranking moments too.
Happy to help :)
(I've had a hard time trying to get this project working in Go, but switched to Rust cause of the shitty garbage collector in Go).
It also helps me learning Rust :)

**Comment by Power2All** [comment] 2023-04-24 20:55
@davidpdrsn 
```
2023-04-24 20:54:49.229256777 [ERROR][torrust_axum::http_service] internal error: entered unreachable code: router=Router { path_router: PathRouter { routes: {RouteId(2): MethodRouter(MethodRouter { get: BoxedHandler, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: Default(Route), allow_header: Bytes(b"GET,HEAD") }), RouteId(3): MethodRouter(MethodRouter { get: BoxedHandler, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: Default(Route), allow_header: Bytes(b"GET,HEAD") }), RouteId(1): MethodRouter(MethodRouter { get: BoxedHandler, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: Default(Route), allow_header: Bytes(b"GET,HEAD") }), RouteId(4): MethodRouter(MethodRouter { get: BoxedHandler, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: Default(Route), allow_header: Bytes(b"GET,HEAD") })}, node: Node { paths: {RouteId(3): "/scrape", RouteId(2): "/announce/:key", RouteId(1): "/announce", RouteId(4): "/scrape/:key"} } }, fallback_router: PathRouter { routes: {RouteId(1): MethodRouter(MethodRouter { get: None, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: BoxedHandler, allow_header: Skip }), RouteId(2): MethodRouter(MethodRouter { get: None, head: None, delete: None, options: None, patch: None, post: None, put: None, trace: None, fallback: BoxedHandler, allow_header: Skip })}, node: Node { paths: {RouteId(1): "/", RouteId(2): "/*__private__axum_fallback"} } }, default_fallback: false }; version=HTTP/1.1; method=CONNECT; uri=www.yahoo.com:443; headers={"host": "www.yahoo.com:443", "user-agent": "Go-http-client/1.1"} CONNECT www.yahoo.com:443 {"host": "www.yahoo.com:443", "user-agent": "Go-http-client/1.1"} request panicked!```

Got this error logged.

**Comment by davidpdrsn** [comment] 2023-04-24 21:40
Indeed it was helpful! I have a minimal reproduction now!

The fallback was totally normal so I was thinking it had to do with something else. Most likely that someone is trying to proxy through your app, since they're sending a `CONNECT` request. And you can indeed repro the panic with:

```rust
use axum::Router;

#[tokio::main]
async fn main() {
    let app = Router::new().fallback(|| async {});

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}
```

Run that and then `curl -x http://127.0.0.1:3000 https://example.com/`. 

That hits the panic:

```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /Users/david.pedersen/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.16/src/routing/mod.rs:312:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll investigate further!

**Comment by Power2All** [comment] 2023-04-24 21:51
Awesome !
Hopefully it will become stable again, so I can update the Axum to latest version again.
Thanks for your support on helping me finding the problem too :)

**Comment by davidpdrsn** [comment] 2023-04-24 22:15
> Hopefully it will become stable again

Definitely! I expect to have a fix out by the end of the week.

**Comment by davidpdrsn** [comment] 2023-04-25 08:37
https://github.com/tokio-rs/axum/pull/1958 should fix it. You are able to test with `7c4cdf787044d`?

**Comment by Power2All** [comment] 2023-04-25 10:43
> #1958 should fix it. You are able to test with [7c4cdf7](https://github.com/tokio-rs/axum/commit/7c4cdf787044d29664688ec9bae87889d3183627)?

Testing now with this.
Will let it run for 30 minutes, unless it panic kills itself again.
Should know soon enough if it works or not.

**Comment by Power2All** [comment] 2023-04-25 11:50
@davidpdrsn No issues anymore, your fix solved it permanently, thanks !
Shall I close the ticket, so you can make a merge request or something ?

**Comment by davidpdrsn** [comment] 2023-04-25 12:04
Great!

I'd like to close the issue by merging the PR. That way GitHub links them together.

**Closed** 2023-04-25 13:58 UTC
Labels: C-bug, A-axum

**Comment by Power2All** [comment] 2023-04-25 19:19
I think there is still a performance problem with the latest version.
Will check with v0.6.12 again to see if it still has a performance problem eventually.
Loading from the service is very slow eventually, so something seems to be up.

**Comment by davidpdrsn** [comment] 2023-04-25 19:29
I did a bunch of benchmarking for another issue and nesting is faster in 0.6.13+ whereas fallbacks are a bit slower. Otherwise performance should be the same.
