### ISSUE TITLE
websockets initial messages delayed multiple seconds

### ISSUE THREAD

**Issue by rukai** [tokio-rs/axum#1961] opened 2023-04-25 13:21 UTC
- [x] I have looked for existing issues (including closed) about this

### Version

axum 0.6 and latest git

### Platform

Linux memes 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux

### Crates

axum

### Description

Please refer to this repo that reproduces the issues https://github.com/rukai/axum/tree/websockets_bug_report
Run
`axum/examples/websockets/src> cargo run --bin example-websockets`
and
`axum/examples/websockets/src> cargo run --bin example-client`

I create a websocket handler on the server which responds with many messages for each message that the client sends it.

The server sends each message 1 second apart, but the client receives the first 3 messages all at once after 3 seconds. From that point things proceed reasonably
Instead of this behavior I expect the initial messages to arrive immediately after being sent.

In my application I had these much more severe scenarios occur:
* no messages arriving until the server closes the connection after about 30s
* no messages arriving until the client has sent 14 messages over about 14s

but I couldnt recreate these severe cases in a simple scenario.
My application is running over a network which may be making the issue worse than the simple localhost test in the reproduced example.

Possibly this is a tungstenite issue, but figured I'd start by reporting it here.

**Comment by davidpdrsn** [comment] 2023-04-25 13:42
Either I don't understand what you mean or I cannot reproduce it.

This is what I see

https://user-images.githubusercontent.com/718941/234295606-f0c2a9a6-6bda-400a-9a97-bf5b14f68701.mov

**Comment by rukai** [comment] 2023-04-25 22:27
Looks like you have main checked out instead of the branch I linked.
These are the changes to the example: https://github.com/tokio-rs/axum/commit/f1cbd6b16a47ae3893a8342cec5b627c10eaa7ab

**Comment by davidpdrsn** [comment] 2023-04-26 07:42
Ah I see. I just `git clone`d your fork, but I see it now. I tried setting `no_delay` on the tcp stream but that didn't change it.

It's most likely a thing with tungstenite though. Axum's web sockets are a very thin wrapper around tungstenite.

I'll close this for now but feel free to ask follow up questions.

**Closed as not planned by davidpdrsn** 2023-04-26 07:42 UTC

**Comment by rukai** [comment] 2023-04-26 10:59
Thankyou for at least confirming you can reproduce it, I've now reproduced it without axum involved and will take it up with the tungstenite project.
