### ISSUE TITLE
URL path with trailing slash does not match wildcard if a route without a trailing slash exists

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [tokio-rs/axum#1986] opened 2023-05-04 00:28 UTC
- [x] I have looked for existing issues (including closed) about this

### Version

Axum 0.6.18

### Platform

Arch Linux x86_64

### Description

Example program:

```rust
use axum::{Router, routing::get};

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/path/foo", get(path_foo))
        .route("/path/*rest", get(wildcard))
        .fallback(fallback);

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn wildcard() -> &'static str {
    "Wildcard route!"
}

async fn path_foo() -> &'static str {
    "path/foo route!"
}

async fn fallback() -> &'static str {
    "Fallback route!"
}

```

Requesting `/path/foo/` (note trailing slash that is not in the route) should match the wildcard route `/path/*rest`, but instead, the fallback route is ran. Commenting out the `/path/foo` route causes the wildcard route to be taken instead of the fallback.

**Comment by ColonelThirtyTwo** [comment] 2023-05-07 01:52
May be related - if there is a route with a normal parameter at the end of it, and the request path is any descendant of that route, the fallback will be taken, even if a wildcard matches:

```rust
use axum::{Router, routing::get, extract::Path};

#[tokio::main]
async fn main() {
    let app = Router::new()
        .route("/path/foo/:arg", get(path_foo))
        .route("/path/*rest", get(wildcard))
        .fallback(fallback);

    axum::Server::bind(&"0.0.0.0:3000".parse().unwrap())
        .serve(app.into_make_service())
        .await
        .unwrap();
}

async fn wildcard() -> &'static str {
    "Wildcard route!"
}

async fn path_foo(Path(arg): Path<String>) -> String {
    format!("path/arg route, arg: {}", arg)
}

async fn fallback() -> &'static str {
    "Fallback route!"
}
```

```text
> curl localhost:3000/path/foo/arg
path/arg route, arg: arg⏎
> curl localhost:3000/path/foo/arg/
Fallback route!⏎
> curl localhost:3000/path/foo/arg/bar
Fallback route!⏎
```

Changing `"/path/foo/:arg"` to `"/path/foo/:arg/"` causes the wildcard route to be taken for descendant paths:

```text
> curl localhost:3000/path/foo/arg/
path/arg route, arg: arg⏎
> curl localhost:3000/path/foo/arg/bar
Wildcard route!⏎
```

**Comment by jplatte** [comment] 2023-05-07 07:48
This seems like it's probably a bug in matchit, which axum uses for routing. It would be nice if somebody could try reproducing with just that, and reporting a bug there if reproduction is successful. (and please link to the new issue here then)

**Comment by ColonelThirtyTwo** [comment] 2023-05-08 12:45
Filed https://github.com/ibraheemdev/matchit/issues/31

**Comment by davidpdrsn** [comment] 2023-05-08 13:30
Thanks! In that case I'll close this issue since its not actionable from axum.

**Closed by davidpdrsn** 2023-05-08 13:30 UTC
Labels: C-bug
